### ISSUE TITLE
Is it possible to implement mouse gestures with this?

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [christoph-heinrich/pointer_event#1]
As the title.

**Comment by christoph-heinrich** [comment]
When it recognizes a dragging event, it locks in horizontal dragging or vertical dragging and then either calls `drag_horizontal(dx)` or `drag_vertical(dy)` on each update. That is useful for things like adjusting volume on vertical swipe without triggering seeking from horizontal swiping. I've already tried it on a touch device running kwin on wayland and it works great.

However `drag(dx, dy)` always gets called when there is a dragging update, and so it would also be possible to recognize more complicated shapes with that.

**Comment by christoph-heinrich** [comment]
I've made it configurable and updated the example. Now you can receive script messages for dragging in your own source file. That should make experimenting with recognizing more complicated shapes more comfortable.

The config might change at some point (e.g. restricting the dragging stuff to script messages only because anything else doesn't make much sense), but it's good enough for now.

If you ever make something that reliably recognizes different shapes, I wouldn't mind merging it :wink:.
